//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicLevel
    {
        public AcademicLevel()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public int IDAcademic { get; set; }
        public string AcademicName { get; set; }
    
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
