//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllInfoContract
    {
        public string IDContract { get; set; }
        public string ContractName { get; set; }
        public string IDType { get; set; }
        public string TypeName { get; set; }
    }
}
