//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllInfoStaffCourse
    {
        public int IDStaffCourse { get; set; }
        public string IDStaff { get; set; }
        public string StaffName { get; set; }
        public string IDCourse { get; set; }
        public string CourseName { get; set; }
        public Nullable<int> Point { get; set; }
        public string Result { get; set; }
    }
}
