//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public string IDStaff { get; set; }
        public string ContractName { get; set; }
        public string NumberContract { get; set; }
        public string IDType { get; set; }
    
        public virtual ContractType ContractType { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
