//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Insurance
    {
        public Insurance()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public string IDInsurance { get; set; }
        public string InsuranceName { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual ICollection<Staff> Staffs { get; set; }
    }
}
