//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveAbsence
    {
        public int IDLeaveAbsence { get; set; }
        public string IDStaff { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> TotalDay { get; set; }
        public string Descript { get; set; }
        public string Status { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
