//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportSalaryDaily
    {
        public int IDReport { get; set; }
        public string IDStaff { get; set; }
        public Nullable<System.DateTime> Month { get; set; }
        public Nullable<int> SalaryAmount { get; set; }
    }
}
