//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.UserCourses = new HashSet<UserCourse>();
        }
    
        public string IDStaff { get; set; }
        public string StaffName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Place { get; set; }
        public string CCCD { get; set; }
        public string Numberphone { get; set; }
        public string IDSalary { get; set; }
        public string IDDepartment { get; set; }
        public string IDInsurance { get; set; }
        public string IDContract { get; set; }
        public string IDStaffCource { get; set; }
        public string IDPosition { get; set; }
        public string Status { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Department Department { get; set; }
        public virtual Insurance Insurance { get; set; }
        public virtual Position Position { get; set; }
        public virtual Salary Salary { get; set; }
        public virtual UserCourse UserCourse { get; set; }
        public virtual Timekeeping Timekeeping { get; set; }
        public virtual ICollection<UserCourse> UserCourses { get; set; }
    }
}
