//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.LeaveAbsences = new HashSet<LeaveAbsence>();
            this.StaffInsurances = new HashSet<StaffInsurance>();
            this.Timekeepings = new HashSet<Timekeeping>();
            this.StaffCourses = new HashSet<StaffCourse>();
        }
    
        public string IDStaff { get; set; }
        public string StaffName { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Place { get; set; }
        public string CCCD { get; set; }
        public Nullable<System.DateTime> DateRange { get; set; }
        public string IssueBy { get; set; }
        public Nullable<int> IDNation { get; set; }
        public Nullable<int> IDAcademic { get; set; }
        public Nullable<int> IDSpecialize { get; set; }
        public string Image { get; set; }
        public string Numberphone { get; set; }
        public string Email { get; set; }
        public string IDDepartment { get; set; }
        public string IDInsurance { get; set; }
        public Nullable<int> IDStaffCoursce { get; set; }
        public string IDPosition { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> Remain { get; set; }
        public string Status { get; set; }
    
        public virtual AcademicLevel AcademicLevel { get; set; }
        public virtual Account Account { get; set; }
        public virtual Contract Contract { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<LeaveAbsence> LeaveAbsences { get; set; }
        public virtual Nation Nation { get; set; }
        public virtual Position Position { get; set; }
        public virtual Salary Salary { get; set; }
        public virtual Specialize Specialize { get; set; }
        public virtual StaffCourse StaffCourse { get; set; }
        public virtual ICollection<StaffInsurance> StaffInsurances { get; set; }
        public virtual ICollection<Timekeeping> Timekeepings { get; set; }
        public virtual ICollection<StaffCourse> StaffCourses { get; set; }
    }
}
