//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCourse
    {
        public UserCourse()
        {
            this.Staffs = new HashSet<Staff>();
        }
    
        public int IDStaffCoursce { get; set; }
        public string IDStaff { get; set; }
        public string IDCourse { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<Staff> Staffs { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
